name: Build fimware


on: 
  workflow_dispatch:
  push:
    branches: main

jobs:
  Build_fimware:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Copy files and init repo
      run: |
        git submodule update --init
        cp -r LPK micropython/ports
        cd micropython
        git submodule update --init
        cp ../lpk.h lib/pico-sdk/src/boards/include/boards
    - name: mpy-cross
      run: |
        cd micropython
        make -C mpy-cross -j4
    - name: Install build dep
      run: sudo apt install -y gcc-arm-none-eabi
    - name: Build
      run: |
        cd micropython/ports/LPK
        make BOARD=LPK submodules -j4
        make BOARD=LPK clean -j4
        make BOARD=LPK -j4
    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.3.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: micropython/ports/LPK/build-LPK/firmware.uf2
        asset_name: 'fimware-${{ runner.arch }}-${{ github.run_id }}.uf2'
        tag: ${{ github.ref }}
        body: '${{ github.ref }}-${{ github.run_id }}'
