name: Build fimware


on: 
  workflow_dispatch:
  push:
    branches: main

jobs:
  Build_fimware:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Copy files
      run: |
        cp -r LPK micropython/ports
    - name: mpy-cross
      run: |
        cd micropython
        make -C mpy-cross
    - name: Build
      run: |
        sudo apt install gcc-arm-none-eabi
        cd micropython/ports/LPK
        make BOARD=LPK submodules -j4
        make BOARD=LPK clean -j4
        make -j4
    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.3.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: micropython/ports/LPK/build/firmware.uf2
        asset_name: 'fimware-${{ matrix.arch }}.uf2'
        tag: ${{ github.ref }}-${{github.head_ref}}
