name: Build fimware


on: 
  workflow_dispatch:
  push:
    branches: main

jobs:
  Build_fimware:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Copy files and init repo
      run: |
        git clone  https://github.com/micropython/micropython
        cp -r RDK/* micropython/ports/rp2/
        cd micropython
        git submodule update --init
        cp ../rdk.h lib/pico-sdk/src/boards/include/boards
    - name: mpy-cross
      run: |
        cd micropython
        make -C mpy-cross -j4
    - name: Install build dep
      run: sudo apt install -y gcc-arm-none-eabi
    - name: Build
      run: |
        cd micropython/ports/rp2
        make BOARD=RDK submodules -j4
        make BOARD=RDK clean -j4
        make BOARD=RDK -j4
    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.3.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: micropython/ports/rp2/build-RDK/firmware.uf2
        asset_name: 'RDK_MPY-fimware-${{ runner.os }}_${{ runner.arch }}-${{ github.ref_name }}-${{ github.run_id }}.uf2'
        body: '${{ github.ref_name }}-${{ github.run_id }}'
        tag: build-${{ github.run_id }}
